appInfo:
  name: server name
  details: server details
  summery: server summery
database:
  dbHost: localhost
  dbPort: 5432
  dbName: 1234
  dbUsername: postgres
  dbPassword: 1234
  logFile:
    name: gorm-log.txt
    dest: ./logs
webServer:
  security:
    loginPath: /login
    logoutPath: /logout
    tokenExpireInMinute: 1
    usernameParamName: username
    passwordParamName: password
  setupPath: /setup
  port: 443
  sllCRT: ./ssl/certificate.crt
  sslKey: ./ssl/privatekey.key
  logFile:
    name: fiber-log.txt
    dest: ./logs